#!/usr/bin/ruby
require 'tty-prompt'
require 'rainbow'
prompt = TTY::Prompt.new

choice = prompt.select("Which shell would you like to make default", cycle: true) do |menu|
  menu.choice 'Mksh', :mksh
  menu.choice 'Bash', :bash
  menu.choice '❌ Exit', :exit
end
# TODO: cat out /etc/shells and take the last work of each option and put it into the list of choices
# also copy the path to that shell for example /bin/bash and make it execute the linux change shell command

logout = Rainbow("Logout for this to take effect").yellow

case choice
when :mksh
  system('chsh -s /bin/mksh')
  puts logout
when :bash
  system('chsh -s /bin/bash')
  puts logout
when :exit
  puts "Exited"
end

